Update issue templates
Kira272921/vscode-themed-portfolio pull request #13
Opened 2022-02-21 14:23 UTC by TechStudent11

2022-02-21 14:25 UTC, KendallDoesCoding commented
@TechStudent11 What about the feature request template?

2022-02-21 14:28 UTC, KendallDoesCoding requested changes

2022-02-21 14:28 UTC, KendallDoesCoding commented on .github/ISSUE_TEMPLATE/bug_report.md
> +labels: ''
```suggestion
labels: 'bug'
```

Add bug label to any issues created under the "Bug Report" issue template.

2022-02-21 14:28 UTC, KendallDoesCoding commented on .github/ISSUE_TEMPLATE/bug_report.md
> +title: ''
```suggestion
title: '[BUG REPORT]:- (Enter short, one sentence summary of bug here)'
```

Add title to Bug Report issue template.

2022-02-21 14:28 UTC, KendallDoesCoding commented on .github/ISSUE_TEMPLATE/bug_report.md
> +name: Bug report
```suggestion
name: 🐛 Bug Report
```

Update name of issue template.

2022-02-21 14:28 UTC, KendallDoesCoding commented on .github/ISSUE_TEMPLATE/bug_report.md
> +about: Create a report to help us improve
```suggestion
about: Create a report to help us improve the project :)
```

2022-02-21 15:53 UTC, Kira272921 commented
Thanks for the lovely suggestions @KendallDoesCoding and also thanks a lot @TechStudent11 for creating a PR

2022-02-21 15:55 UTC, merged

2022-02-21 16:02 UTC, KendallDoesCoding commented
> Thanks for the lovely suggestions @KendallDoesCoding and also thanks a lot @TechStudent11 for creating a PR

Welcome. I don't think https://github.com/Kira272921/vscode-themed-portfolio/pull/13/files/cbbb8e61c73b399a6e3c04724c987ed130868368#diff-185833cb26d7ac66a4d39042fd576a820c2c2c6d05ad18973bb9c7dce77267c5 got merged in for some reason.

2022-02-21 16:42 UTC, TechStudent11 commented
@KendallDoesCoding ah sorry I used GitHub's tool to create it. Looks like it wasn't effective. Thanks for noticing.

@Kira272921 No problem!

2022-02-21 17:02 UTC, KendallDoesCoding commented
> @KendallDoesCoding ah sorry I used GitHub's tool to create it. Looks like it wasn't effective. Thanks for noticing.
> 
> @Kira272921 No problem!

No issues! It's weird that Github's tool doesn't automatically add the label as bug tho.

2022-03-04 13:12 UTC, Kira272921 commented
@all-contributors please add @TechStudent11 for doc